sentence =str(input("enter a sentence to convert it to genz")).lower()
sentence=sentence.split()
import random

gen_alpha_dictionary = {
    "internet meme": "meme",
    "friend group": "squad",
    "relationship goals": "couple goals",
    "fashionable": "stylish",
    "snack": "munchies",
    "hang out": "chill",
    "celebrate": "party",
    "gossip": "tea",
    "apology": "sorry",
    "excuse me": "my bad",
    "overthinking": "thinking too much",
    "get together": "meetup",
    "family": "fam",
    "silly": "goofy",
    "fear": "scare",
    "thrill": "rush",
    "creativity": "imagination",
    "personal space": "bubble",
    "socializing": "mixing",
    "goodbye gift": "send-off present",
    "selfie": "pic",
    "message": "dm",
    "curious": "nosy",
    "homework assignment": "school task",
    "exercise class": "fitness session",
    "new experience": "adventure",
    "big deal": "major thing",
    "regular": "standard",
    "regularly": "often",
    "future plans": "goals",
    "study group": "study buddies",
    "old school": "retro",
    "neighborhood": "block",
    "parents' house": "rents' place",
    "favorite show": "binge-worthy",
    "crush": "liking",
    "hangry": "hungry and angry",
    "sweetheart": "babe",
    "job": "gig",
    "boss": "supervisor",
    "college": "uni",
    "university": "school",
    "student": "learner",
    "home office": "remote workspace",
    "meeting place": "venue",
    "group project": "team assignment",
    "celebration": "bash",
    "special occasion": "big day",
    "trophy": "award",
    "responsibility": "task",
    "goal": "aim",
    "step back": "take a break",
    "hang out spot": "chill zone",
    "late night": "night owl hours",
    "early morning": "morning vibes",
    "nice day": "good weather",
    "cooking": "food prep",
    "shopping spree": "retail therapy",
    "budget": "money plan",
    "expenses": "spending",
    "breakdown": "meltdown",
    "support system": "squad",
    "emotional support": "moral support",
    "wish": "dream",
    "aspiration": "goal",
    "celebrity": "famous person",
    "news update": "scoop",
    "online shopping": "web buying",
    "home-cooked meal": "home grub",
    "emotional intelligence": "feeling smarts",
    "friendship bracelet": "bestie band",
    "personal growth": "self-improvement",
    "mental health": "mind wellness",
    "favorite color": "best hue",
    "podcast": "audio show",
    "television series": "tv show",
    "video game": "gaming title",
    "gaming console": "game system",
    "virtual reality": "VR",
    "streaming service": "streaming platform",
    "fan base": "fandom",
    "charity": "cause",
    "volunteering": "helping out",
    "sustainability": "eco-friendliness",
    "climate change": "earth issues",
    "support group": "helping circle",
    "comfort zone": "safe space",
    "relationship advice": "couple tips",
    "dating": "seeing someone",
    "self-care": "me time",
    "work-life balance": "life harmony",
    "weekend getaway": "short trip",
    "fun fact": "cool tidbit",
    "road trip": "car adventure",
    "camping": "outdoor sleepover",
    "friendship goals": "squad goals",
    "overreacting": "drama queen",
    "weekend plans": "fun agenda",
    "house party": "get-together",
    "favorite book": "must-read",
    "book club": "reading group",
    "mindfulness": "being present",
    "positive vibes": "good energy",
    "inspiration": "motivation",
    "life hack": "smart tip",
    "role model": "idol",
    "happy place": "comfort zone",
    "advice": "tips",
    "documentary": "info film",
    "challenge": "test",
    "brainstorming": "idea session",
    "meme culture": "internet humor",
    "kickback": "relaxed hangout",
    "community service": "volunteer work",
    "environment": "nature",
    "wildlife": "animals",
    "music festival": "live event",
    "party theme": "bash style",
    "crowd": "group of people",
    "roadblock": "obstacle",
    "hustle culture": "grind mindset",
    "life choices": "decisions",
    "self-expression": "showing self",
    "big picture": "overall view",
    "relationship status": "dating situation",
    "school project": "class task",
    "work schedule": "job plan",
    "vacation plans": "trip ideas",
    "time management": "schedule skills",
    "school spirit": "team pride",
    "social interaction": "mixing with others",
    "experience": "know-how",
    "risk-taking": "adventure seeking",
    "saying goodbye": "parting ways",
    "homework help": "study aid",
    "advice column": "tips section",
    "favorite activity": "best pastime",
    "personal style": "fashion sense",
    "healthcare": "wellness services",
    "trophy case": "award display",
    "gift card": "present voucher",
    "dream job": "ideal career",
    "social life": "friend circle",
    "secret admirer": "crush",
    "influencer": "content creator",
    "check-in": "update",
    "outfit": "fit",
    "hot topic": "buzz issue",
    "networking": "connections",
    "side hustle": "extra gig",
    "first impression": "initial vibe",
    "grateful": "thankful",
    "bucket list": "dream list",
    "core values": "beliefs",
    "inspiration board": "vision board",
    "teamwork": "collab",
    "risk": "chance",
    "feedback": "input",
    "highlight": "best moment",
    "adventure park": "amusement spot",
    "school trip": "educational outing",
    "group chat": "text thread",
    "sibling rivalry": "bro-sis banter",
    "relationship drama": "love issues",
    "test results": "grades",
    "famous quote": "classic saying",
    "health food": "nutritious eats",
    "confidence": "self-assurance",
    "mindset": "attitude",
    "personality": "character",
    "interests": "hobbies",
    "guilty pleasure": "indulgence",
    "personal brand": "self-image",
    "trend": "current style",
    "achievement": "success",
    "nostalgia": "memory trip",
    "reunion": "get-together",
    "bonding": "connecting",
    "passion project": "dream project",
    "learning curve": "growth phase",
    "cultural exchange": "sharing traditions",
    "service project": "volunteer effort",
    "career path": "job journey",
    "team player": "collaborator",
    "resilience": "bounce back",
    "life lesson": "learning moment",
    "problem-solving": "finding solutions",
    "motivation speaker": "inspirational speaker",
    "personal finance": "money management",
    "career goals": "job aspirations",
    "network": "connections",
    "involvement": "participation",
    "bond": "connection",
    "friend zone": "platonic area",
    "power nap": "quick sleep",
    "future self": "next you",
    "upcycling": "creative reuse",
    "creative outlet": "artistic expression",
    "time out": "break time",
    "supportive friend": "ride or die",
    "favorite memory": "best moment",
    "positive affirmations": "good vibes",
    "safety net": "support system",
    "risky business": "gamble",
    "inner peace": "calm",
    "social justice": "equality work",
    "self-improvement": "personal growth",
    "hello": "hi",
    "goodbye": "bye",
    "friend": "buddy",
    "cool": "lit",
    "thank you": "thx",
    "sorry": "oops",
    "excited": "stoked",
    "fun": "awesome",
    "crazy": "wild",
    "money": "coins",
    "love": "heart",
    "bad": "not great",
    "really?": "no way!",
    "I don't know": "dunno",
    "see you later": "laters",
    "what's up?": "sup?",
    "good": "great",
    "awesome": "amazing",
    "let's go": "let's do it!",
    "drama": "tea",
    "tired": "pooped",
    "cute": "adorbs",
    "chill": "relax",
    "party": "get-together",
    "workout": "exercise",
    "best friend": "bff",
    "talk": "chat",
    "home": "place",
    "funny": "hilarious",
    "very": "super",
    "sleep": "nap",
    "difficult": "hard",
    "situation": "thing",
    "favorite": "best",
    "good morning": "morning!",
    "good night": "nighty night",
    "eat": "nom",
    "disappointed": "bummed",
    "amazing": "epic",
    "cool person": "legend",
    "truth": "real talk",
    "relationship": "friendship",
    "nice": "sweet",
    "stressful": "a lot",
    "smart": "brainy",
    "brave": "cool",
    "help": "assist",
    "information": "info",
    "fashion": "style",
    "annoying": "ugh",
    "happy": "happy vibes",
    "sad": "feels",
    "like": "enjoy",
    "popular": "famous",
    "old": "vintage",
    "new": "fresh",
    "crazy": "insane",
    "fail": "oops",
    "hard work": "effort",
    "best": "top",
    "worst": "lame",
    "adult": "grown-up",
    "strange": "weird",
    "beautiful": "gorgeous",
    "exciting": "thrilling",
    "boring": "meh",
    "talented": "skilled",
    "busy": "swamped",
    "overwhelmed": "stressed",
    "party": "bash",
    "information": "details",
    "details": "info",
    "hanging out": "chillin'",
    "let's do it": "sure!",
    "homework": "school work",
    "internet": "web",
    "social media": "socials",
    "gift": "present",
    "work": "hustle",
    "meeting": "hangout",
    "cool down": "calm down",
    "problems": "issues",
    "breakfast": "breaky",
    "lunch": "lunch",
    "dinner": "dinner",
    "shopping": "buying stuff",
    "class": "lesson",
    "school": "learning place",
    "teachers": "educators",
    "parents": "rents",
    "movie": "film",
    "television": "tv",
    "computer": "device",
    "phone": "cell",
    "car": "ride",
    "travel": "go places",
    "fun times": "good times",
    "happy birthday": "bday!",
    "congratulations": "congrats!",
    "good job": "nice work!",
    "failure": "miss",
    "problem": "issue",
    "vacation": "trip",
    "exercise": "move",
    "dance": "groove",
    "music": "tunes",
    "record": "drop",
    "song": "track",
    "artist": "singer",
    "concert": "show",
    "event": "happening",
    "surprise": "wow",
    "message": "text",
    "news": "updates",
    "life": "journey",
    "time": "quater past midnight",
    "workout routine": "exercise plan",
    "quick": "fast",
    "slow": "take it easy",
    "difficult": "tough",
    "secret": "hidden",
    "adventure": "journey",
    "life goal": "dream",
    "team": "crew",
    "happiness": "joy",
    "disappointment": "letdown",
    "feeling": "emotion",
    "knowledge": "smarts",
    "style": "aesthetic",
    "motivation": "drive",
    "future": "what's next",
    "cry": "sob",
    "crying": "tearing up",
    "cried": "teared up",
    "laugh": "giggle",
    "laughing": "cracking up",
    "laughed": "chuckled",
    "play": "game",
    "playing": "gaming",
    "played": "gamed",
    "eat": "grub",
    "eating": "munching",
    "ate": "chowed down",
    "drink": "sip",
    "drinking": "sipping",
    "drank": "gulped",
    "run": "sprint",
    "running": "jogging",
    "ran": "flew",
    "work": "hustle",
    "working": "grinding",
    "worked": "busted",
    "study": "cram",
    "studying": "hit the books",
    "studied": "learned",
    "money":"vbucks",
    "talk": "chat",
    "talking": "chit-chatting",
    "talked": "spoke",
    "see": "peep",
    "seeing": "watching",
    "saw": "spotted",
    "have": "got",
    "having": "holding",
    "had": "kept",
    "go": "bounce",
    "going": "rolling",
    "went": "pulled up",
    "make": "create",
    "making": "crafting",
    "made": "produced",
    "give": "send",
    "giving": "donating",
    "gave": "hooked up",
    "find": "discover",
    "finding": "unearthing",
    "found": "located",
    "help": "assist",
    "helping": "aiding",
    "helped": "supported",
    "buy": "cop",
    "buying": "purchasing",
    "bought": "copped",
    "sell": "flip",
    "selling": "hawking",
    "sold": "moved",
        "no-go area": "friend zone",
    "chill pad": "hangout spot",
    "social butterfly": "party animal",
    "pic pole": "selfie stick",
    "flashback": "throwback",
    "treat day": "cheat day",
    "show off": "flex",
    "marathon": "binge-watch",
    "flop": "fail",
    "vacay": "trip",
    "amazing stuff": "awesome sauce",
    "food lover": "foodie",
    "fake friend": "frenemy",
    "chaotic situation": "hot mess",
    "awkward moment": "cringe",
    "kill it": "slay",
    "adaptability": "flexibility",
    "fear of missing out": "FOMO",
    "you only live once": "YOLO",
    "joy of missing out": "JOMO",
    "vibe": "mood",
    "excitement": "hype",
    "inspiration": "inspo",
    "on point": "snatched",
    "great": "fire",
    "awesome": "lit",
    "desperate": "thirsty",
    "influence": "clout",
    "transformation": "glow up",
    "friendship aspirations": "squad goals",
    "being grown-up": "adulting",
    "infatuation": "crush",
    "emotional pain": "heartbreak",
    "love issues": "relationship drama",
    "crew": "squad",
    "favorite": "fave",
    "not cool": "lame",
    "aspirations": "goals",
    "wake-up call": "reality check",
    "do great": "slay",
    "excited": "stoked",
    "energy": "vibe",
    "personal time": "self-care",
    "emoticon": "emoji",
    "tag": "hashtag",
    "glamorous": "glam",
    "sharing gossip": "spilling the tea",
    "challenge someone": "call-out",
    "perfectly done": "on fleek",
    "family or friends": "fam",
    "not too obvious": "low-key",
    "totally obvious": "high-key",
    "over the top": "extra",
    "mainstream": "basic",
    "group of friends": "squad",
    "no disrespect": "no shade",
    "evidence": "receipts",
    "go for it": "send it",
    "very exciting": "that’s lit",
    "small bite": "snack",
    "working hard": "on the grind",
    "good atmosphere": "it’s a vibe",
    "annoying thing": "pet peeve",
    "making an effort": "putting in work",
    "great insult": "sick burn",
    "really cool": "totally tubular",
    "made me happy": "made my day",
    "harmful": "toxic",
    "reveal secrets": "spill the beans",
    "show up": "come through",
    "let's go": "bring it on",
    "for what it’s worth": "just saying",
    "listen to me": "hear me out",
    "wait a minute": "hold up",
    "be modest": "stay humble",
    "hang out": "kick it",
    "not normal": "out of pocket",
    "revolutionary idea": "game changer",
    "relatable feeling": "big mood",
    "expose": "put it on blast",
    "be creative": "think outside the box",
    "improve": "level up",
    "emotionally affected": "in your feelings",
    "constantly thinking about": "living rent-free",
    "stay alert": "look alive",
    "be genuine": "keep it 100",
    "accept loss": "take the L",
    "doing well": "crushing it",
    "advanced": "next level",
    "uninformed": "out of the loop",
    "relax": "vibe out",
    "recover": "bounce back",
    "deal with it later": "cross that bridge",
    "great": "cool beans",
    "stay relaxed": "keep it chill",
    "be honest": "speak your truth",
    "make money": "get the bag",
    "don’t argue with me": "don’t at me",
    "too intense": "no chill",
    "not noticed": "under the radar",
    "exposed": "on blast",
    "stay awesome": "stay golden",
    "take action": "make it happen",
    "don’t give up": "keep pushing",
    "be strong": "stay fierce",
    "calm down": "take a seat",
    "make a difference": "be the change",
    "stay alert": "stay sharp",
    "organize yourself": "get it together",
    "get up and work hard": "rise and grind",
    "get to the point": "cut to the chase",
    "go all out": "full send",
    "try it": "give it a shot",
    "postpone": "rain check",
}
 
 
new=[]
words_straight_out_of_ohio=["ohio","sigma","rizz","rizzler","sus","sussy","bussy","bussin","level 10 rizz","gyatt","level 100","level 1 crook","skibidi","senpai","skibidi toilet"]
for i in range((len(sentence)//3)):
    susrandom=random.choice(words_straight_out_of_ohio)
    while True:
        prev=""
        randompos=random.randint(0,len(sentence))
        if randompos==prev:
            continue
        else:
            break
    prev=randompos
    sentence.insert(randompos,susrandom)
for word in sentence:
    try:
        new.append(gen_alpha_dictionary[word])
    except KeyError:
        new.append(word)
 
newsentence=" ".join(new)
print("")
print("")
print(newsentence)

with open("output.txt", "w", encoding='utf-8') as file:
    file.write(newsentence)

import pyttsx3
engine = pyttsx3.init()
engine.say(newsentence)
engine.runAndWait()

